// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA9t2SM2VBvSMb5Fghi1uZ5KPwJkgnwE4',
    appId: '1:708066671296:web:d66a27250c290302e60b25',
    messagingSenderId: '708066671296',
    projectId: 'neurorelief-bcc32',
    authDomain: 'neurorelief-bcc32.firebaseapp.com',
    storageBucket: 'neurorelief-bcc32.firebasestorage.app',
    measurementId: 'G-XKL6XD1ML2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo4NKbZNgX682Xjk_by1Cbfe2YZQ564mM',
    appId: '1:708066671296:android:fcb65bfcf784191ce60b25',
    messagingSenderId: '708066671296',
    projectId: 'neurorelief-bcc32',
    storageBucket: 'neurorelief-bcc32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZOupSk2MFs7641-6JUR6cDc9bAEA5Neo',
    appId: '1:708066671296:ios:41e738c6bdbb773ee60b25',
    messagingSenderId: '708066671296',
    projectId: 'neurorelief-bcc32',
    storageBucket: 'neurorelief-bcc32.firebasestorage.app',
    iosBundleId: 'com.example.neurelief',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZOupSk2MFs7641-6JUR6cDc9bAEA5Neo',
    appId: '1:708066671296:ios:41e738c6bdbb773ee60b25',
    messagingSenderId: '708066671296',
    projectId: 'neurorelief-bcc32',
    storageBucket: 'neurorelief-bcc32.firebasestorage.app',
    iosBundleId: 'com.example.neurelief',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDA9t2SM2VBvSMb5Fghi1uZ5KPwJkgnwE4',
    appId: '1:708066671296:web:82ef83ac58e72ffce60b25',
    messagingSenderId: '708066671296',
    projectId: 'neurorelief-bcc32',
    authDomain: 'neurorelief-bcc32.firebaseapp.com',
    storageBucket: 'neurorelief-bcc32.firebasestorage.app',
    measurementId: 'G-GZF509E7F7',
  );
}
